<?php
/**
 * Implements hook_preprocess_page().
 */
function superhero_pagetitle_preprocess_page(&$vars) {
  // Preemptively set the 'breadcrumb' variable, so that template_process_page()
  // performs nothing, and this module can render the breadcrumb as a block
  // instead.
	if(!path_is_admin(current_path())){
		$vars['title'] = '';
	}
}

/**
 * Implements hook_block_info().
 */
function superhero_pagetitle_block_info() {
  $blocks['superhero_pagetitle'] = array(
    'info' => t('Superhero Page Title'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function superhero_pagetitle_block_view($delta) {
  $block = array();
  if ($delta == 'superhero_pagetitle') {
    $block['content'] = '<h2 class="page_title">'.drupal_get_title().'</h2>';
  }
  return $block;
}