<?php

/**
 * @file
 * Creates new view modes and sets up views
 */
 
/**
 * Implements hook_entity_info_alter
 */
function superhero_display_entity_info_alter(&$entity_info) {
	// Add a view mode for a second teaser style
	$entity_info['node']['view modes']['teaser_alt'] = array(
		'label' => t('Teaser alt'),
		'custom settings' => TRUE,
	);
}

/**
 * Implements hook_preprocess_node
 */
function superhero_display_preprocess_node(&$vars) {
	if ($vars['view_mode'] == 'teaser_alt') {
		$vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__teaser_alt';
		$vars['classes_array'][] = 'node-teaser-alt';
	}
}
