<?php

function ostpc_menu(){
 $items['settings_appearance']=array(
   'title'		=>	t('Settings'),
   'description'	=>	t('Страница настроек сайта.'),
   'page callback'	=>	'setting_page',
   'access arguments'	=>	array('access ostpc module'),
   'type'		=>	MENU_NORMAL_ITEM,
  );
  $items['settings_watermark']=array(
   'title'		=>	t('Watermark'),
   'description'	=>	t('Страница настроек водного знака.'),
   'page callback'	=>	'setting_wm',
   'access arguments'	=>	array('access ostpc module'),
   'type'		=>	MENU_NORMAL_ITEM,
  );
 return $items;
}

function ostpc_permission() {
    return array(
        'access ostpc module' => array(
              'title'           => t('Access to OSTPC page setting'),
              'description'     => t('Доступ к странице настроек')
            ),
        );
}

function setting_page(){
	$form = drupal_get_form('ostpc_form'); //получаем поля формы
	$form = drupal_render($form); //рендерим форму
	return $form;
}

function setting_wm(){
	$form = drupal_get_form('ostpc_wm_form'); //получаем поля формы
	$form = drupal_render($form); //рендерим форму
	return $form;
}

function ostpc_variable_info($options) {

  $variable['ostpc_logo'] = array(
    'title' => t('Logo Path'),
  );
  
  $variable['ostpc_width'] = array(
    'title' => t('Logo width'),
  );
  
  $variable['ostpc_height'] = array(
    'title' => t('Logo height'),
  );

  $variable['ostpc_background'] = array(
    'title' => t('Background Path'),
  );
  
  $variable['ostpc_wm_text'] = array(
    'title' => t('WM text'),
  );
  
  $variable['ostpc_wm_color'] = array(
    'title' => t('WM color'),
  );
  
  $variable['ostpc_wm_alpha'] = array(
    'title' => t('WM alpha'),
  );
  
  $variable['ostpc_wm_h'] = array(
    'title' => t('WM horizontal'),
  );
  
  $variable['ostpc_wm_v'] = array(
    'title' => t('WM vertical'),
  );
  
  return $variable;
}

function ostpc_wm_form($form, &$form_state){
	$form=array();
	
	$form['field_text'] = array(
		'#type'	=> 'textfield',
		'#title' => t('Текст водного знака'),
		'#default_value' => variable_get('ostpc_wm_text'),
	);
	
	$form['field_color'] = array(
		'#type' => 'textfield',
		'#title' => t('Цвет водного знака'),
		'#suffix' => '<div id="color-picker"></div>',
		'#default_value' => variable_get('ostpc_wm_color'),
		'#maxlength' => 7,
		'#size' => 7,
		'#attached' => array(
			'library' => array(
				array('system', 'farbtastic'),
			),
			'js' => array(
				array(
					'type' => 'inline',
					'data' =>
						'(function($) {
							$(document).ready(function() {
								$("#color-picker").farbtastic("#edit-field-color");
						});
					}) (jQuery);'
				),
			)
		)
	);
	
	$form['field_alpha'] = array(
		'#type'	=> 'textfield',
		'#title' => t('Прозрачность водного знака'),
		'#maxlength' => 3,
		'#description' => t('Введите значение прозрачности от 0 до 100.'),
		'#default_value' => variable_get('ostpc_wm_alpha'),
	);
	
	$form['field_horizontal_position'] = array(
		'#type' => 'select',
		'#title' => t('Horizontal position of watermark'),
		'#options' => array(0 => t('left'), 1 => t('middle'), 2 => t('right')),
		'#default_value' => variable_get('ostpc_wm_h'),
	);
	$form['field_vertical_position'] = array(
		'#type' => 'select',
		'#title' => t('Vertical position of watermark'),
		'#options' => array(0 => t('top'), 1 => t('center'), 2 => t('bottom')),
		'#default_value' => variable_get('ostpc_wm_v'),
	);
	
	$form['submit'] = array( //кнопка сабмит
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	
	//$form['#after_build'][] = 'add_js';
 
	return $form;
}

function ostpc_wm_form_submit($form, &$form_state){
	/*print '<pre>';
	print_r($form_state);
	die();*/
	if(intval($form_state['values']['field_alpha'])>=0 && intval($form_state['values']['field_alpha'])<=100){
		variable_set('ostpc_wm_text',$form_state['values']['field_text']);
		variable_set('ostpc_wm_color',$form_state['values']['field_color']);
		variable_set('ostpc_wm_alpha', intval($form_state['values']['field_alpha']));
		variable_set('ostpc_wm_h', intval($form_state['values']['field_horizontal_position']));
		variable_set('ostpc_wm_v', intval($form_state['values']['field_vertical_position']));
	}
	else{
		drupal_set_message("Вы ввели неправильное значение прозрачности", 'error');
	}
}

function ostpc_form($form, &$form_state){
	$form=array();
	
	$form['field_logo_width'] = array(
		'#type'	=> 'textfield',
		'#title' => t('Ширина логотипа'),
		'#default_value' => variable_get('ostpc_width'),
	);
	
	$form['field_logo_height'] = array(
		'#type'	=> 'textfield',
		'#title' => t('Высота логотипа'),
		'#default_value' => variable_get('ostpc_height'),
	);
	
	$form['logo_button'] = array(
	  '#prefix' => '<div class="wrap-div"><label class="title">'. t('Логотип сайта') .'</label><img class="path_to_logo" src="'.variable_get('ostpc_logo').'"/>',
	  '#suffix' => '</div>',
	  '#markup' => '<button id="bt_for_logo" class="btn big blue"><span>' . t('Изменить логотип') . '</span></button>',
	);
	
	$form['logo'] = array(
		'#type' => 'hidden',
		'#default_value' => variable_get('ostpc_logo'),
	);
	
	$form['bg_button'] = array(
	  '#prefix' => '<div class="wrap-div"><label class="title">'. t('Фон сайта') .'</label><img class="path_to_background" src="'.variable_get('ostpc_background').'"/>',
	  '#suffix' => '</div>',
	  '#markup' => '<button id="bt_for_bg" class="btn big blue"><span>' . t('Изменить фон') . '</span></button>',
	);
		
	$form['background'] = array(
		'#type' => 'hidden',
		'#default_value' => variable_get('ostpc_background'),
	);	
	
	$form['submit'] = array( //кнопка сабмит
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	
	$form['#after_build'][] = 'add_js';
 
	return $form;
}

function ostpc_form_submit($form, &$form_state){
	variable_set('ostpc_logo', $form_state['values']['logo']);
	variable_set('ostpc_background', $form_state['values']['background']);
	variable_set('ostpc_width', $form_state['values']['field_logo_width']);
	variable_set('ostpc_height', $form_state['values']['field_logo_height']);
}

function add_js($form, &$form_state){
	drupal_add_js(drupal_get_path('module', 'ostpc') . "/load_imce.js");
	return $form;
}